### ISSUE TITLE
Would be nice to have `fontSize` attribute in `FormItemPassword` like `FormItemTextField` does. 

### ISSUE THREAD

**Issue by Njima1572** [mathrunet/flutter_masamune#1]
When I was trying to use the `FormItemPassword` with `FormItemTextField`, I found that `FormItemTextField` has fontSize attribute, however, `FormItemPassword` does not. It would be nice to create this attribute to keep the UI consistent.

https://github.com/mathrunet/flutter_masamune/blob/d6eb4503ff8bb61eb20823880089f6f91b13c89a/lib/form/form_item_password.dart#L4-L29

https://github.com/mathrunet/flutter_masamune/blob/e1947c4e90a8c3059f9eb38a9f0e7143d604c8ee/lib/form/form_item_text_field.dart#L4-L52

**Comment by mathrunet** [comment]
I'm thinking of deprecating FormItemPassword.
It can be substituted by putting two FormItemTextField in a row and setting `obscureText` to `true`.
```
FormItemTextField(
  labelText: "Password".localize(),
  keyboardType: TextInputType.visiblePassword,
  obscureText: true,
  onSaved: (value) {
    if (value.isEmpty) {
      return;
    }
    context["password"] = value;
  },
),
FormItemTextField(
  labelText: "Password Confirmationn".localize(),
  keyboardType: TextInputType.visiblePassword,
  obscureText: true,
  onSaved: (value) {
    if (value.isEmpty) {
      return;
    }
    context["confirmPassword"] = value;
  },
),
```
