### ISSUE TITLE
Info about katana_router

### ISSUE THREAD

**Issue by SAGARSURI** [mathrunet/flutter_masamune#11]
Hey @mathrunet 

The katana_router package looks really promising. Since its relatively new, I wanted to know if it's production ready?

**Comment by mathrunet** [comment]
@sagarsuri 
Thank you.

katana_router is used in several products I am involved with, but
It is still subject to frequent updates.

It is still subject to frequent updates, especially with the planned evolution of the Dart language, such as support for macros.
（The interface will be kept the same as much as possible.)

The package is stable when used within the product, so please consider using the product with the above possibilities in mind.

**Comment by SAGARSURI** [comment]
Thanks for the response. I have another question:

Currently I am building a mobile app whose features are distributed in different packages. Every feature package will have a screen. Can this plugin handle multi package architecture?

**Comment by mathrunet** [comment]
Basically, pages can be moved by passing AnyPage.query() to the router, so it can be used without problems even if pages are spread across multiple packages.

However, when using path names such as on the Web, it is necessary to make sure that the paths of each page do not overlap in advance.

**Comment by SAGARSURI** [comment]
Thank you so much for the info. Keep up the great work.
