### ISSUE TITLE
Katana Router - Query url param

### ISSUE THREAD

**Issue by carmas123** [mathrunet/flutter_masamune#4]
Hi, I use Katana Router into my web project. My problem is that I don't know how can I handle and pass a query encoded value to second page like this:

`http://myapp.com/search?s=searched_value`

How can I handle and pass the "s" query to page?

**Comment by mathrunet** [comment]
Thanks for using it.

My apologies. The query parameter, but it is currently not implemented as a feature yet.

I will add it in the next update.

And I will let you know when I update it again.

**Comment by carmas123** [comment]
Thank you so much

**Comment by mathrunet** [comment]
@carmas123 
This feature is supported in ver1.9.0.

**Comment by carmas123** [comment]
Wou you are the best 💪
