### ISSUE TITLE
Parameter of ScopedValueRef.fetch()

### ISSUE THREAD

**Issue by nknotats** [mathrunet/flutter_masamune#6]
Hi,

https://github.com/mathrunet/flutter_masamune/blob/233771749b2d127af72670dd9611a8ece8c3aff6/packages/katana_scoped/lib/value/fetch.dart#L22-L24

I guess it seem to be used '[ ]' instead of '{ }'.

```
  T? fetch<T>({
    String? name,
  }) {
```

**Comment by mathrunet** [comment]
@nknotats 

NamedParameter so that it can be explicitly identified as `name`.
