### ISSUE TITLE
Error - Generating Katana Localization file

### ISSUE THREAD

**Issue by jamescardona11** [mathrunet/flutter_masamune#7]
After configuring and running the build_runner, the katana.localize file never generated

This is my initial configuration:
`import 'package:katana_localization/katana_localization.dart';

part 'localization.localize.dart';

@GoogleSpreadSheetLocalize(
  'https://docs.google.com/spreadsheets/d/1bw7IXEr7BGkZ4U6on0OuF7HQkTMgDSm6u5ThpBkDPeo/edit#gid=551986808',
  version: 1,
)
class AppLocalize extends _$AppLocalize {}
`

`[WARNING] katana_localization_builder on lib/core/services/localization.dart:
Null check operator used on a null value: #0      LocalizeLoader.load (package:katana_localization_builder/src/loader.dart:85:41)
<asynchronous suspension>
#1      GoogleSpreadSheetLocalizeGenerator.generateForAnnotatedElement (package:katana_localization_builder/generator/localize_generator.dart:42:7)
<asynchronous suspension>`

**Comment by mathrunet** [comment]
@jamescardona11 

Thank you for your report.

Could you please give us the following information?
- Result of "flutter doctor -v"
- Version of katana_localization and katana_localization_builder in use
- Contents of ".dart_tool/katana/localization.1.csv" of the project using build_runner


---
ご報告ありがとうございます。

下記の情報をいただけますでしょうか？
・flutter doctor -vの結果
・使用しているkatana_localization、katana_localization_builderのバージョン
・build_runnerを使用したプロジェクトの.dart_tool/katana/localization.1.csvの中身

よろしくお願いいたします。
