### ISSUE TITLE
Router generator issues

### ISSUE THREAD

**Issue by JCKodel** [mathrunet/flutter_masamune#8]
1) When a Widget has an argument, the generated QueryBuilder doesn't work:

```dart
@PagePath("/error")
class ErrorPage extends StatelessWidget {
  const ErrorPage({required this.exception, super.key});

   static const query = _$ErrorPageQuery();

  final Object exception;
}
```

Generated _$ErrorPageQuery extends RouteQueryBuilder:

```dart
RouteQuery? resolve(String? path) {
    if (path == null) {
      return null;
    }
    if (path.contains("?")) {
      final split = path.split("?");
      final match = _regExp.firstMatch(split.first.trimString("/"));
      if (match == null) {
        return null;
      }
      final query = Uri.splitQueryString(split.last);
      return _$_ErrorPageQuery(
        path,
      );
```

That last line doesn't compile (**The named parameter 'exception' is required**).

Also, on _$_ErrorPageQuery:

```dart
String get _parameters {
    final _query = <String, String>{};
    return _query.isEmpty
        ? ""
        : "?${_query.entries.map((e) => "${e.key}=${e.value}").join("&")}";
  }
```

In that scope, `_query` is an invalid name (it should not have `_`). An warning **The local variable `_query` starts with an underscore**. And warnings ARE errors.

**Comment by mathrunet** [comment]
@JCKodel 
This issue was fixed.

Please update as we are deploying to pub.
--

修正しました。

pubの方にもデプロイしてますので更新してください。
