### ISSUE TITLE
FireStore以外のデータストアとの接続について

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [mathrunet/flutter_masamune#9]
こんにちは。[こちら](https://zenn.dev/mathru/books/d219c9b7cdfd53)の本を読んでおります。
大変興味があるのですが、このフレームワークはリモートにデータを永続化させる場合Firestoreを使用することが前提となっておりますでしょうか？Supabaseなど別のデータソースと接続することも想定されておりますか？（例えば、interfaceを実装しさえすれば可能など）

また、フレームワークを使用する際に使用したい機能だけを指定して使用したい（例えば状態管理だけはRiverpodを使用したい）といった場合は本フレームワークは不向きでしょうか？

このフレームワークに興味を持っており、使用してアプリ作成をしたいと思っております。
どうぞよろしくお願いします。

**Comment by mathrunet** [comment]
@ShuheiSuzuki-07 
ありがとうございます

>大変興味があるのですが、このフレームワークはリモートにデータを永続化させる場合Firestoreを使用することが前提となっておりますでしょうか？Supabaseなど別のデータソースと接続することも想定されておりますか？（例えば、interfaceを実装しさえすれば可能など）

Firebase（Firestore）への接続については`ModelAdapter`というベースクラスを元に作られております。
なのでそのインターフェースを元にSupabaseなどに接続するアダプターを作れば可能です。

ドキュメントとコレクションというデータ構造を守る、パスに応じて値を取得するといった制約はございますが基本的にはどのデータソースでも接続可能に設計しております。

実績としてはMySQLとLaravelのバックエンド構成でアダプターを特別に実装し接続したことがございます。

>また、フレームワークを使用する際に使用したい機能だけを指定して使用したい（例えば状態管理だけはRiverpodを使用したい）といった場合は本フレームワークは不向きでしょうか？

下記zennの記事ですがMasamuneフレームワークは機能別の細かいパッケージ群（katana_xxx）をまとめて利用可能にしたフレームワークとなります。
https://zenn.dev/mathru

なので状態管理だけはRiverpodを使うといったことも可能です。

ただ、自動生成周り（katana_cliやmasamune_builder）といったものはすべてMasamuneフレームワークで利用することを前提としたものを生成しているので、katanaコマンドで生成した後のファイルに追記したり書き換えたりの作業は必要になります。

ドキュメントやコレクション、コントローラーなどの内部で状態を管理しているオブジェクトに関してはすべてChangeNotifierを継承しているものなのでRiverpodやGetXなどの他パッケージを使って状態管理を行うといったことも可能です。

**Comment by ShuheiSuzuki-07** [comment]
@mathrunet 
> ドキュメントとコレクションというデータ構造を守る、パスに応じて値を取得するといった制約はございますが基本的にはどのデータソースでも接続可能に設計しております。

制約はあるものの可能であること承知しました。

> なので状態管理だけはRiverpodを使うといったことも可能です。
> 
> ただ、自動生成周り（katana_cliやmasamune_builder）といったものはすべてMasamuneフレームワークで利用することを前提としたものを生成しているので、katanaコマンドで生成した後のファイルに追記したり書き換えたりの作業は必要になります。

こちらも承知しました。

ぜひ使用してみたいと思います！今後ドキュメントがさらに整備されると嬉しいですしそれに貢献できたらなと思います。

ありがとうございました。
